# Numpy

In [75]:
import numpy as np
import pandas as pd

In [21]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [22]:
np.eye(8,dtype = int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [23]:
np.random.rand(2,5) # uniform distribution

array([[0.44563157, 0.21868827, 0.23415627, 0.16840138, 0.05574544],
       [0.98580036, 0.84652536, 0.30819102, 0.69954831, 0.09166173]])

In [24]:
np.random.randn(2,4) # normal distribution

array([[-0.41722094, -0.45395678,  0.08944914,  0.77011575],
       [-1.60266937,  0.26290325,  1.07794889, -0.69526194]])

In [25]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [49]:
sample_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
sample_matrix[1,0]

4

Array Slicing

In [51]:
sample_matrix[2,:-1]

array([7, 8])

In [52]:
sample_matrix[2]

array([7, 8, 9])

In [53]:
sample_matrix[:,(0,1)]

array([[1, 2],
       [4, 5],
       [7, 8]])

Selection Technique

In [94]:
sample_array = np.arange(1,21)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [95]:
rand_array = np.random.randint(0,10,30)
rand_array

array([3, 4, 4, 9, 9, 8, 0, 6, 1, 2, 7, 9, 1, 7, 8, 4, 0, 0, 4, 8, 1, 4,
       2, 6, 5, 1, 2, 1, 9, 9])

In [96]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [97]:
sample_array.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [98]:
np.dot(sample_matrix.T,sample_matrix)

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [99]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [100]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [101]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])

In [102]:
np.max(sample_array)

20

In [103]:
np.min(sample_array)

1

In [104]:
np.argmax(sample_array)

19

In [105]:
np.argmin(sample_array)

0

In [106]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [107]:
np.std(sample_array)

5.766281297335398

In [108]:
np.var(sample_array)

33.25

In [109]:
np.mean(sample_array)

10.5

In [110]:
array = np.random.randn(3,4)
array

array([[-1.43245686, -0.34294922,  0.53593574, -1.21182805],
       [ 0.83260056, -1.57053304,  0.90763654, -0.50087622],
       [-0.10368953,  0.53246171,  1.93077769, -1.41615117]])

In [111]:
np.round(array,decimals=2)

array([[-1.43, -0.34,  0.54, -1.21],
       [ 0.83, -1.57,  0.91, -0.5 ],
       [-0.1 ,  0.53,  1.93, -1.42]])

In [112]:
sports=np.array(['golf','baseball','fball','baseball'])
np.unique(sports)

array(['baseball', 'fball', 'golf'], dtype='<U8')